title: "Peridendes"
logo: /assets/images/nC2R.gif
email: peridendes@reacher.me
description: A page for potential.
tags:
  - GitHub
  - GitHub Pages
url: ""
github_username: peridendes
encoding: utf-8
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
show_downloads: false
include: [".well-known"]
